// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/catalog/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/catalog/[id].get').default>>>>
    }
    '/home': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/home.get').default>>>>
    }
    '/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/search.get').default>>>>
    }
    '/sources': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/sources.get').default>>>>
    }
    '/test': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/test').default>>>>
    }
  }
}
export {}